namespace GenerateSuppressions.CodeRules;

internal static class StyleCop
{
    internal static List<CodeRule> Rules =
        [
            // Readability
            new CodeRule("SA1100", "A call to a member from an inherited class begins with base., and the local class does not contain an override or implementation of the member.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1101", "A call to an instance member of the local class or a base class is not prefixed with 'this.', within a C# code file.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1102", "A C# query clause does not begin on the same line as the previous clause, or on the next line.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1103", "The clauses within a C# query expression are not all placed on the same line, and each clause is not placed on its own line.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1104", "A clause within a C# query expression begins on the same line as the previous clause, when the previous clause spans across multiple lines.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1105", "A clause within a C# query expression spans across multiple lines, and does not begin on its own line.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1106", "The C# code contains an extra semicolon.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1107", "The C# code contains more than one statement on a single line.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1108", "A C# statement contains a comment between the declaration of the statement and the opening brace of the statement.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1109", "A C# statement contains a region tag between the declaration of the statement and the opening brace of the statement.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1110", "The opening parenthesis or bracket in a call to a C# method or indexer, or the declaration of a method or indexer, is not placed on the same line as the method or indexer name.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1111", "The closing parenthesis or bracket in a call to a C# method or indexer, or the declaration of a method or indexer, is not placed on the same line as the last parameter.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1112", "The closing parenthesis or bracket in a call to a C# method or indexer, or the declaration of a method or indexer, is not placed on the same line as the opening bracket when the element does not take any parameters.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1113", "A comma between two parameters in a call to a C# method or indexer, or in the declaration of a method or indexer, is not placed on the same line as the previous parameter.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1114", "The start of the parameter list for a method or indexer call or declaration does not begin on the same line as the opening bracket, or on the line after the opening bracket.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1115", "A parameter within a C# method or indexer call or declaration does not begin on the same line as the previous parameter, or on the next line.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1116", "The parameters to a C# method or indexer call or declaration span across multiple lines, but the first parameter does not start on the line after the opening bracket.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1117", "The parameters to a C# method or indexer call or declaration are not all on the same line or each on a separate line.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1118", "A parameter to a C# method or indexer, other than the first parameter, spans across multiple lines.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1120", "The C# comment does not contain any comment text.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1121", "The code uses one of the basic C# types, but does not use the built-in alias for the type.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1122", "The C# code includes an empty string, written as \"\".", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1123", "The C# code contains a region within the body of a code element.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1124", "The C# code contains a region.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1125", "The Nullable type has been defined not using the C# shorthand.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1126", "A call to a member is not prefixed with the 'this.', 'base.', 'object.' or 'typename.' prefix to indicate the intended method call, within a C# code file.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1127", "A generic constraint on a type or method declaration is on the same line as the declaration, within a C# code file.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1128", "A constructor initializer is on the same line as the constructor declaration, within a C# code file.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1129", "A value type was constructed using the syntax new T().", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1130", "An anonymous method was declared using the form delegate (parameters) { }, when a lambda expression would provide equivalent behavior with the syntax (parameters) => { }.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1131", "A comparison was made between a variable and a literal or constant value, and the variable appeared on the right-hand side of the expression.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1132", "Two or more fields were declared in the same field declaration syntax.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1133", "Two or more attributes appeared within the same set of square brackets.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1134", "An attribute is placed on the same line of code as another attribute or element.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1135", "A using directive is not qualified.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1136", "Multiple enum values are placed on the same line of code.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1137", "Two sibling elements which each start on their own line have different levels of indentation.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1139", "Use literal suffix notation instead of casting.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1141", "Use tuple syntax instead of the underlying ValueTuple implementation type.", "StyleCop.CSharp.ReadabilityRules"),
            new CodeRule("SA1142", "An element of a tuple was referenced by its metadata name when an element name is available.", "StyleCop.CSharp.ReadabilityRules"),

            // Ordering
            new CodeRule("SA1200", "A C# using directive is placed outside of a namespace element.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1201", "An element within a C# code file is out of order in relation to the other elements in the code.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1202", "An element within a C# code file is out of order within regard to access level, in relation to other elements in the code.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1203", "A constant field is placed beneath a non-constant field.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1204", "A static element is positioned beneath an instance element of the same type.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1205", "The partial element does not have an access modifier defined.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1206", "The keywords within the declaration of an element do not follow a standard ordering scheme.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1207", "The keyword protected is positioned after the keyword internal within the declaration of a protected internal C# element.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1208", "A using directive which declares a member of the System namespace appears after a using directive which declares a member of a different namespace, within a C# code file.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1209", "A using-alias directive is positioned before a regular using directive.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1210", "The using directives within a C# code file are not sorted alphabetically by namespace.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1211", "The using-alias directives within a C# code file are not sorted alphabetically by alias name.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1212", "A get accessor appears after a set accessor within a property or indexer.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1213", "An add accessor appears after a remove accessor within an event.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1214", "A readonly field is positioned beneath a non-readonly field.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1215", "An instance readonly element is positioned beneath an instance non-readonly element of the same type.", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1216", "A using static directive is positioned at the wrong location (before a regular using directive or after an alias using directive).", "StyleCop.CSharp.OrderingRules"),
            new CodeRule("SA1217", "The using static directives within a C# code file are not sorted alphabetically by full type name.", "StyleCop.CSharp.OrderingRules"),

            // Naming
            new CodeRule("SA1300", "The name of a C# element does not begin with an upper-case letter.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1301", "There are currently no situations in which this rule will fire.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1302", "The name of a C# interface does not begin with the capital letter I.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1303", "The name of a constant C# field should begin with an upper-case letter.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1304", "The name of a non-private readonly C# field should being with an upper-case letter.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1305", "The name of a field or variable in C# uses Hungarian notation.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1306", "The name of a field in C# does not begin with a lower-case letter.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1307", "The name of a public or internal field in C# does not begin with an upper-case letter.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1308", "A field name in C# is prefixed with m_ or s_.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1309", "A field name in C# begins with an underscore.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1310", "A field name in C# contains an underscore.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1311", "The name of a static readonly field does not begin with an upper-case letter.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1312", "The name of a variable in C# does not begin with a lower-case letter.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1313", "The name of a parameter in C# does not begin with a lower-case letter.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1314", "The name of a C# type parameter does not begin with the capital letter T.", "StyleCop.CSharp.NamingRules"),
            new CodeRule("SA1316", "Element names within a tuple type should have the correct casing.", "StyleCop.CSharp.NamingRules"),

            // Maintainability
            new CodeRule("SA1119", "A C# statement contains parenthesis which are unnecessary and should be removed.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1400", "The access modifier for a C# element has not been explicitly defined.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1401", "A field within a C# class has an access modifier other than private.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1402", "A C# code file contains more than one unique type.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1403", "A C# code file contains more than one namespace.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1404", "A Code Analysis SuppressMessage attribute does not include a justification.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1405", "A call to Debug.Assert in C# code does not include a descriptive message.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1406", "A call to Debug.Fail in C# code does not include a descriptive message.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1407", "A C# statement contains a complex arithmetic expression which omits parenthesis around operators.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1408", "A C# statement contains a complex conditional expression which omits parenthesis around operators.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1409", "A C# file contains code which is unnecessary and can be removed without changing the overall logic of the code.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1410", "A call to a C# anonymous method does not contain any method parameters, yet the statement still includes parenthesis.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1411", "An attribute declaration does not contain any parameters, yet it still includes parenthesis.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1412", "The encoding of the file is not UTF-8 with byte order mark.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1413", "A multi-line initializer should use a comma on the last item.", "StyleCop.CSharp.MaintainabilityRules"),
            new CodeRule("SA1414", "Tuple types appearing in member declarations should have explicitly named tuple elements.", "StyleCop.CSharp.MaintainabilityRules"),

            // Layout
            new CodeRule("SA1500", "The opening or closing brace within a C# statement, element, or expression is not placed on its own line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1501", "A C# statement containing opening and closing braces is written completely on a single line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1502", "A C# element containing opening and closing braces is written completely on a single line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1503", "The opening and closing braces for a C# statement have been omitted.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1504", "Within a C# property, indexer or event, at least one of the child accessors is written on a single line, and at least one of the child accessors is written across multiple lines.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1505", "An opening brace within a C# element, statement, or expression is followed by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1506", "An element documentation header above a C# element is followed by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1507", "The C# code contains multiple blank lines in a row.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1508", "A closing brace within a C# element, statement, or expression is preceded by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1509", "An opening brace within a C# element, statement, or expression is preceded by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1510", "Chained C# statements are separated by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1511", "The while footer at the bottom of a do-while statement is separated from the statement by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1512", "A single-line comment within C# code is followed by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1513", "A closing brace within a C# element, statement, or expression is not followed by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1514", "An element documentation header above a C# element is not preceded by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1515", "A single-line comment within C# code is not preceded by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1516", "Adjacent C# elements are not separated by a blank line.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1517", "The code file has blank lines at the start.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1518", "The line endings at the end of a file do not match the settings for the project.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1519", "The opening and closing braces for a multi-line C# statement have been omitted.", "StyleCop.CSharp.LayoutRules"),
            new CodeRule("SA1520", "The opening and closing braces of a chained if/else if/else construct were included for some clauses, but omitted for others.", "StyleCop.CSharp.LayoutRules"),

            // Documentation
            new CodeRule("SA1600", "A C# code element is missing a documentation header.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1601", "A C# partial element is missing a documentation header.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1602", "An item within a C# enumeration is missing an Xml documentation header.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1603", "The Xml within a C# element's document header is badly formed.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1604", "The Xml header documentation for a C# element is missing a <summary> tag.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1605", "The <summary> or <content> tag within the documentation header for a C# code element is missing or empty.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1606", "The <summary> tag within the documentation header for a C# code element is empty.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1607", "The <summary> or <content> tag within the documentation header for a C# code element is empty.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1608", "The <summary> tag within an element's Xml header documentation contains the default text generated by Visual Studio during the creation of the element.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1609", "The Xml header documentation for a C# property does not contain a <value> tag.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1610", "The Xml header documentation for a C# property contains an empty <value> tag.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1611", "A C# method, constructor, delegate or indexer element is missing documentation for one or more of its parameters.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1612", "The documentation describing the parameters to a C# method, constructor, delegate or indexer element does not match the actual parameters on the element.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1613", "A <param> tag within a C# element's documentation header is missing a name attribute containing the name of the parameter.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1614", "A <param> tag within a C# element's documentation header is empty.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1615", "A C# element is missing documentation for its return value.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1616", "The <returns> tag within a C# element's documentation header is empty.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1617", "A C# code element does not contain a return value, or returns void, but the documentation header for the element contains a <returns> tag.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1618", "A generic C# element is missing documentation for one or more of its generic type parameters.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1619", "A generic, partial C# element is missing documentation for one or more of its generic type parameters, and the documentation for the element contains a <summary> tag.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1620", "The <typeparam> tags within the Xml header documentation for a generic C# element do not match the generic type parameters on the element.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1621", "A <typeparam> tag within the Xml header documentation for a generic C# element is missing a name attribute, or contains an empty name attribute.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1622", "A <typeparam> tag within the Xml header documentation for a generic C# element is empty.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1623", "The documentation text within a C# property's <summary> tag does not match the accessors within the property.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1624", "The documentation text within a C# property's <summary> tag takes into account all of the accessors within the property, but one of the accessors has limited access.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1625", "The Xml documentation for a C# element contains two or more identical entries, indicating that the documentation has been copied and pasted.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1626", "The C# code contains a single-line comment which begins with three forward slashes in a row.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1627", "The Xml header documentation for a C# code element contains an empty tag.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1628", "A section of the Xml header documentation for a C# element does not begin with a capital letter.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1629", "A section of the Xml header documentation for a C# element does not end with a period (also known as a full stop).", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1630", "A section of the Xml header documentation for a C# element does not contain any whitespace between words.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1631", "A section of the Xml header documentation for a C# element does not contain enough alphabetic characters.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1632", "From StyleCop 4.5 this rule is disabled by default.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1633", "A C# code file is missing a standard file header.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1634", "The file header at the top of a C# code file is missing a copyright tag.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1635", "The file header at the top of a C# code file is missing copyright text.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1636", "The file header at the top of a C# code file does not contain the appropriate copyright text.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1637", "The file header at the top of a C# code file is missing the file name.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1638", "The file tag within the file header at the top of a C# code file does not contain the name of the file.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1639", "The file header at the top of a C# code file does not contain a filled-in summary tag.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1640", "The file header at the top of a C# code file does not contain company name text.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1641", "The file header at the top of a C# code file does not contain the appropriate company name text.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1642", "The XML documentation header for a C# constructor does not contain the appropriate summary text.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1643", "The Xml documentation header for a C# finalizer does not contain the appropriate summary text.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1644", "A section within the Xml documentation header for a C# element contains blank lines.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1645", "An included Xml documentation file does not exist.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1646", "An included Xml documentation link contains an invalid path.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1647", "An include tag within an Xml documentation header does not contain valid file and path attribute.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1648", "<inheritdoc> has been used on an element that doesn't inherit from a base class or implement an interface.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1649", "The file name of a C# code file does not match the first type declared in the file.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1650", "The element documentation for the element contains one or more spelling mistakes or unrecognized words.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1651", "The documentation for the element contains one or more <placeholder> elements.", "StyleCop.CSharp.DocumentationRules"),
            new CodeRule("SA1652", "This rule was moved to SA0001", "StyleCop.CSharp.DocumentationRules"),

            // Alternative
            new CodeRule("SX1101", "A call to an instance member of the local class or a base class is prefixed with 'this.', within a C# code file.", "StyleCop.CSharp.AlternativeRules"),
            new CodeRule("SX1309", "A field name does not begin with an underscore.", "StyleCop.CSharp.AlternativeRules"),
            new CodeRule("SX1309S", "A static field name does not begin with an underscore.", "StyleCop.CSharp.AlternativeRules"),

            // Spacing
            new CodeRule("SA1000", "The spacing around a C# keyword is incorrect.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1001", "The spacing around a comma is incorrect, within a C# code file.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1002", "The spacing around a semicolon is incorrect, within a C# code file.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1003", "The spacing around an operator symbol is incorrect, within a C# code file.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1004", "A line within a documentation header above a C# element does not begin with a single space.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1005", "A single-line comment within a C# code file does not begin with a single space.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1006", "A C# preprocessor-type keyword is preceded by space.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1007", "The operator keyword within a C# operator overload method is not followed by any whitespace.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1008", "An opening parenthesis within a C# statement is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1009", "A closing parenthesis within a C# statement is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1010", "An opening square bracket within a C# statement is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1011", "A closing square bracket within a C# statement is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1012", "An opening brace within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1013", "A closing brace within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1014", "An opening generic bracket within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1015", "A closing generic bracket within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1016", "An opening attribute bracket within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1017", "A closing attribute bracket within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1018", "A nullable type symbol within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1019", "The spacing around a member access symbol is incorrect, within a C# code file.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1020", "An increment or decrement symbol within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1021", "A negative sign within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1022", "A positive sign within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1023", "A dereference symbol or an access-of symbol within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1024", "A colon within a C# element is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1025", "The code contains multiple whitespace characters in a row.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1026", "An implicitly typed new array allocation within a C# code file is not spaced correctly.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1027", "The code contains a tab or space character which is not consistent with the current project settings.", "StyleCop.CSharp.SpacingRules"),
            new CodeRule("SA1028", "A line of code ends with a space, tab, or other whitespace characters before the end of line character(s).", "StyleCop.CSharp.SpacingRules"),

            // Special
            new CodeRule("SA0001", "All diagnostics of XML documentation comments has been disabled due to the current project configuration.", "StyleCop.CSharp.SpecialRules"),
            new CodeRule("SA0002", "The stylecop.json settings file could not be loaded due to a deserialization error.", "StyleCop.CSharp.SpecialRules"),
        ];
}
